# Generated by Django 4.0.5 on 2022-06-25 08:54

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='author',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='is_archive',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='title',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='severity',
            name='author',
        ),
        migrations.RemoveField(
            model_name='severity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='severity',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='severity',
            name='is_archive',
        ),
        migrations.RemoveField(
            model_name='severity',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='severity',
            name='title',
        ),
        migrations.RemoveField(
            model_name='severity',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='status',
            name='author',
        ),
        migrations.RemoveField(
            model_name='status',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='status',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='status',
            name='is_archive',
        ),
        migrations.RemoveField(
            model_name='status',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='status',
            name='title',
        ),
        migrations.RemoveField(
            model_name='status',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='priority',
            name='priority',
            field=models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='P0', max_length=2),
        ),
        migrations.AddField(
            model_name='severity',
            name='severity',
            field=models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4')], default='S1', max_length=2),
        ),
        migrations.AddField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ONG', 'Ongoing'), ('PEN', 'Pending'), ('WIT', 'Waiting'), ('SNZ', 'Snooze'), ('BLK', 'Blocked'), ('RES', 'Resolved'), ('CLS', 'Closed'), ('DPL', 'Duplicate')], default='NEW', max_length=3),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 25, 8, 54, 24, 602394, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
