# Generated by Django 4.0.5 on 2022-06-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_remove_priority_author_remove_priority_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Templates',
            new_name='Template',
        ),
        migrations.AlterModelTable(
            name='attachment',
            table='attachment',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='helptopic',
            table='helptopic',
        ),
        migrations.AlterModelTable(
            name='priority',
            table='priority',
        ),
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
        migrations.AlterModelTable(
            name='severity',
            table='severity',
        ),
        migrations.AlterModelTable(
            name='shift',
            table='shift',
        ),
        migrations.AlterModelTable(
            name='status',
            table='status',
        ),
        migrations.AlterModelTable(
            name='template',
            table='templates',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='ticket',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
