# Generated by Django 4.0.5 on 2022-06-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_rename_templates_template_alter_attachment_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_joining',
            field=models.DateTimeField(null=True),
        ),
    ]
